"""Canonical event names used by the local observability layer."""

PYTHON_STARTUP_STARTED = "python.startup.started"
PYTHON_STARTUP_STATE_LOADED = "python.startup.state_loaded"
PYTHON_STARTUP_WS_STARTING = "python.startup.ws_starting"
PYTHON_STARTUP_WS_STARTED = "python.startup.ws_started"
PYTHON_STARTUP_WS_FAILED = "python.startup.ws_failed"
PYTHON_STARTUP_HTTP_STARTING = "python.startup.http_starting"
PYTHON_STARTUP_HTTP_STARTED = "python.startup.http_started"
PYTHON_SHUTDOWN_REQUESTED = "python.shutdown.requested"
PYTHON_SHUTDOWN_COMPLETED = "python.shutdown.completed"

HTTP_REQUEST_RECEIVED = "http.request.received"
HTTP_REQUEST_VALIDATED = "http.request.validated"
HTTP_REQUEST_FAILED_VALIDATION = "http.request.failed_validation"
HTTP_RESPONSE_SENT = "http.response.sent"
HTTP_HANDLER_FAILED = "http.handler.failed"
HTTP_ROUTE_NOT_FOUND = "http.route.not_found"

WS_SERVER_STARTING = "ws.server.starting"
WS_SERVER_STARTED = "ws.server.started"
WS_SERVER_FAILED = "ws.server.failed"
WS_CONNECTION_OPENED = "ws.connection.opened"
WS_HANDSHAKE_PING_SENT = "ws.handshake.ping_sent"
WS_HANDSHAKE_PONG_RECEIVED = "ws.handshake.pong_received"
WS_HANDSHAKE_ACCEPTED = "ws.handshake.accepted"
WS_HANDSHAKE_REJECTED = "ws.handshake.rejected"
WS_CONNECTION_DUPLICATE_REJECTED = "ws.connection.duplicate_rejected"
WS_CONNECTION_REPLACED = "ws.connection.replaced"
WS_CONNECTION_CLOSED = "ws.connection.closed"
WS_KEEPALIVE_PING_SENT = "ws.keepalive.ping_sent"
WS_KEEPALIVE_FAILED = "ws.keepalive.failed"
WS_MESSAGE_SENT = "ws.message.sent"
WS_MESSAGE_RECEIVED = "ws.message.received"
WS_REQUEST_WAIT_STARTED = "ws.request.wait_started"
WS_REQUEST_WAIT_SUCCEEDED = "ws.request.wait_succeeded"
WS_REQUEST_WAIT_TIMEOUT = "ws.request.wait_timeout"
WS_REQUEST_UNEXPECTED_RESPONSE = "ws.request.unexpected_response"

STATE_LOADED = "state.loaded"
STATE_LOAD_FAILED = "state.load_failed"
STATE_SAVED = "state.saved"
STATE_SAVE_FAILED = "state.save_failed"
STATE_PDF_UPSERTED = "state.pdf.upserted"
STATE_PDF_STATUS_TRANSITION = "state.pdf.status_transition"
STATE_PDF_STATUS_TRANSITION_INVALID = "state.pdf.status_transition_invalid"
STATE_PDF_MISSING = "state.pdf.missing"
STATE_FOLDER_CHANGED = "state.folder.changed"
PDF_PENDING_MOVE_STARTED = "pdf.pending_move.started"
PDF_PENDING_MOVE_SUCCEEDED = "pdf.pending_move.succeeded"
PDF_PENDING_MOVE_FAILED = "pdf.pending_move.failed"

WORKFLOW_CREATED = "workflow.created"
WORKFLOW_STARTED = "workflow.started"
WORKFLOW_STEP_STARTED = "workflow.step.started"
WORKFLOW_STEP_SUCCEEDED = "workflow.step.succeeded"
WORKFLOW_STEP_FAILED = "workflow.step.failed"
WORKFLOW_COMPLETED = "workflow.completed"
WORKFLOW_FAILED = "workflow.failed"
WORKFLOW_EXPORT_REQUESTED = "workflow.export.requested"
WORKFLOW_EXPORT_COMPLETED = "workflow.export.completed"
